version: '3.9'
services:
  scouter-server:
    build: ./scouter-server  # Dockerfile 위치 지정
    restart: always
    environment:
      - MGR_PURGE_PROFILE_KEEP_DAYS=2
      - MGR_PURGE_XLOG_KEEP_DAYS=5
      - MGR_PURGE_COUNTER_KEEP_DAYS=15
    ports:
      - "6180:6180"
      - "6100:6100"
      - "6100:6100/udp"
    volumes:
      - ./scouter/logs:/scouter/logs
      - ./scouter/database:/scouter/database

  scouter-paper:
    image: scouterapm/scouter-paper:2.6.4
    restart: always
    ports:
      - "8080:80"
